apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vcwivgb2b-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-14864718c9.f59b.p3.openshiftapps.com/rhtap/rhtap-qe:ec8a90ea765de0c5691906c5a38d908b5832325b@sha256:81e2294efe39bf327c836f163d544a1293c0c2cf23442e41f2c8b0c63968bf62
          name: container-image
